name: 'Use Private Docker Action'
description: 'Action that allows for running docker container actions from private registries'
inputs:
  docker_registry:
    description: 'The registry to pull the private container action from'
    required: false
    default: ghcr.io
  docker_username:
    description: 'The username to use to pull the image'
    required: true
  docker_password:
    description: 'The password to use to pull the image'
    required: true
  package:
    description: 'The image and tag to pull'
    required: true
  inputs:
    description: 'The inputs to use for the private action in a multiline yml string'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker_registry }}
    - ${{ inputs.docker_username }}
    - ${{ inputs.docker_password }}
    - ${{ inputs.package }}
    - ${{ inputs.inputs }}
